spring:
  data:
    mongodb:
      uri: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  port: 8088
  servlet:
    session:
      timeout: 3600

logging:
  level:
    org.springframework: INFO
